# GitLab CI jobs for SDP Workflow library

variables:
  GIT_STRATEGY: clone

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH

stages:
  - test
#  - lint
  - build
  - publish

image: python:latest

# ============================================================================
# Test and lint Python package
# ============================================================================

test:
  stage: test
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  before_script:
    - pip3 install -r requirements.txt -r requirements-test.txt
  script:
    - python3 setup.py test
#  after_script:
#    - mkdir -p build/reports
#    - mv code-coverage.xml unit-tests.xml build/reports
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

lint:
  stage: lint
  dependencies:
    - test
  before_script:
    - pip3 install -r requirements.txt -r requirements-test.txt
  script:
    - pylint --exit-zero --output-format=parseable src/ska_sdp_workflow
    - pylint --exit-zero --output-format=pylint2junit.JunitReporter src/ska_sdp_workflow > linting.xml
  after_script:
    - mkdir -p build/reports
    - mv linting.xml build/reports
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

# ============================================================================
# Build Python package
# ============================================================================

.build_python:
  stage: build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Executed on a non-master commit

build_dev:
  extends: .build_python
  except: [master]
  script:
    - python3 setup.py egg_info -b+dev.$CI_COMMIT_SHORT_SHA sdist bdist_wheel

# Executed on a master commit

build_release:
  extends: .build_python
  only: [master]
  script:
    - python3 setup.py sdist bdist_wheel

# ============================================================================
# Publish Python package (master only)
# ============================================================================

publish:
  stage: publish
#  only: [master]
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  before_script:
    - pip install twine
  script:
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true

# ============================================================================
# CI metrics
# ============================================================================

create_ci_metrics:
  stage: .post
  when: always
  script:
    # Gitlab CI badges creation: START
    - curl -s https://gitlab.com/ska-telescope/ci-metrics-utilities/raw/master/scripts/ci-badges-func.sh | sh
    # Gitlab CI badges creation: END
  artifacts:
    paths:
      - build
    expire_in: 1 week

